name: prompt_vault
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.4.1
  path: ^1.9.1
  intl: ^0.20.2
  share_plus: ^10.1.4

flutter:
  uses-material-design: true
